# 使用官方Python镜像作为基础镜像
FROM python:3.9-slim

# 设置工作目录
WORKDIR /app

# 复制项目文件到工作目录
COPY . /app

# 安装项目依赖
RUN pip install --no-cache-dir -r requirements.txt

# 暴露服务端口
EXPOSE 9191

# 设置环境变量
ENV PYTHONUNBUFFERED=1

# 运行应用
CMD ["python", "run.py"]